import fetch from "node-fetch";
import "dotenv/config";

const API_BASE_URL = process.env.BASE_URL || "http://localhost:3000/api";

const sofas = [
  {
    name: "SofaLux Ebony L-Shaped",
    slug: "sofalux-ebony-l-shaped",
    description: "A spacious L-shaped sofa with storage, perfect for Kenyan living rooms.",
    price: 149999,
    category: "L-Shaped",
    images: [
      "/classic-leather.jpg",
      "/modern-fabric.jpg"
    ],
    material: "Leather",
    colors: ["Black", "Brown"],
    inStock: true,
    seatingCapacity: 5,
    features: ["Storage Compartment", "High-Density Foam", "Stain-Resistant"],
    stockQuantity: 15,
    brand: "SofaLux",
    warranty: "3 years",
    reviews: [],
  },
  {
    name: "Nairobi Comfort Cozy",
    slug: "nairobi-comfort-cozy",
    description: "A modern fabric sofa with plush cushions for ultimate comfort.",
    price: 79999,
    category: "Stationary",
    images: [
      "/modern-fabric.jpg",
      "/vintage-chester.jpg"
    ],
    material: "Fabric",
    colors: ["Gray", "Beige"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Removable Covers", "Anti-Slip Base", "Soft Cushions"],
    stockQuantity: 20,
    brand: "Nairobi Comfort",
    warranty: "2 years",
    reviews: [],
  },
  {
    name: "Vintage Royale Chesterfield",
    slug: "vintage-royale-chesterfield",
    description: "A tufted leather Chesterfield with classic elegance.",
    price: 199999,
    category: "Chesterfield",
    images: [
      "/vintage-chester.jpg",
      "/vintage-chester.jpg"
    ],
    material: "Leather",
    colors: ["Brown", "Burgundy"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Tufted Design", "Hardwood Frame", "Luxury Finish"],
    stockQuantity: 8,
    brand: "Elegance Home",
    warranty: "5 years",
    reviews: [],
  },
  {
    name: "SofaLux Compact Loveseat",
    slug: "sofalux-compact-loveseat",
    description: "A minimalist loveseat for small apartments or cozy corners.",
    price: 59999,
    category: "Loveseat",
    images: [
      "/loveseat.jpg",
      "/sectional.jpg"
    ],
    material: "Fabric",
    colors: ["White", "Gray"],
    inStock: true,
    seatingCapacity: 2,
    features: ["Space-Saving", "Easy-Clean Fabric", "Modern Design"],
    stockQuantity: 25,
    brand: "SofaLux",
    warranty: "1 year",
    reviews: [],
  },
  {
    name: "Family U-Shaped Lounge",
    slug: "family-u-shaped-lounge",
    description: "A large U-shaped sofa for family gatherings, with adjustable headrests.",
    price: 349999,
    category: "U-Shaped",
    images: [
      "/sectional.jpg",
      "/velvet-sofa.jpg"
    ],
    material: "Fabric",
    colors: ["Blue", "Gray"],
    inStock: true,
    seatingCapacity: 7,
    features: ["Adjustable Headrests", "Modular Design", "Plush Cushions"],
    stockQuantity: 5,
    brand: "Kenya Comfort",
    warranty: "4 years",
    reviews: [],
  },
  {
    name: "SofaLux Tech Recliner",
    slug: "sofalux-tech-recliner",
    description: "A reclining sofa with USB ports and built-in footrests.",
    price: 129999,
    category: "Recliner",
    images: [
      "/recliner-sofa.jpg",
      "/velvet-sofa.jpg"
    ],
    material: "Leather",
    colors: ["Beige", "Black"],
    inStock: true,
    seatingCapacity: 3,
    features: ["USB Charging", "Electric Recline", "Cup Holders"],
    stockQuantity: 12,
    brand: "SofaLux",
    warranty: "3 years",
    reviews: [],
  },
  {
    name: "Retro Mid-Century Sofa",
    slug: "retro-mid-century-sofa",
    description: "A mid-century modern sofa with sleek wooden legs.",
    price: 109999,
    category: "Stationary",
    images: [
      "/orange-sofa.jpg",
      "/recliner-sofa.jpg"
    ],
    material: "Wood",
    colors: ["Green", "Mustard"],
    inStock: false,
    seatingCapacity: 3,
    features: ["Wooden Legs", "Retro Design", "Firm Cushions"],
    stockQuantity: 18,
    brand: "Vintage Vibe",
    warranty: "2 years",
    reviews: [],
  },
  {
    name: "SofaLux Guest Sleeper",
    slug: "sofalux-guest-sleeper",
    description: "A convertible sofa bed for guests, with hidden storage.",
    price: 139999,
    category: "Sofa Bed",
    images: [
      "/convertible-sofa.jpg",
      "/orange-sofa.jpg"
    ],
    material: "Fabric",
    colors: ["Charcoal", "Navy"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Foldable Bed", "Storage Drawer", "Easy Conversion"],
    stockQuantity: 10,
    brand: "SofaLux",
    warranty: "2 years",
    reviews: [],
  },
  {
    name: "Luxe Velvet Elegance",
    slug: "luxe-velvet-elegance",
    description: "A luxurious velvet sofa with a soft, elegant touch.",
    price: 159999,
    category: "Stationary",
    images: [
      "/velvet-sofa.jpg",
      "/convertible-sofa.jpg"
    ],
    material: "Velvet",
    colors: ["Navy", "Emerald"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Soft Velvet", "Decorative Piping", "Sturdy Frame"],
    stockQuantity: 15,
    brand: "Luxe Living",
    warranty: "3 years",
    reviews: [],
  },
  {
    name: "Rustic Retreat Sofa",
    slug: "rustic-retreat-sofa",
    description: "A rustic sofa with wooden accents for a cozy vibe.",
    price: 99999,
    category: "Stationary",
    images: [
      "/rustic-sofa.jpg",
      "/convertible-sofa.jpg"
    ],
    material: "Wood",
    colors: ["Brown", "Gray"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Wooden Accents", "Textured Fabric", "Durable Build"],
    stockQuantity: 18,
    brand: "Countryside Homes",
    warranty: "2 years",
    reviews: [],
  },
  {
    name: "SofaLux Sleek Leather",
    slug: "sofalux-sleek-leather",
    description: "A modern leather sofa with a minimalist aesthetic.",
    price: 169999,
    category: "Stationary",
    images: [
      "/sleek-leather.jpg",
      "/sofa-bed.jpg",
    ],
    material: "Leather",
    colors: ["White", "Matte Black", "Gray"],
    inStock: false,
    seatingCapacity: 3,
    features: ["Low-Profile Design", "Easy-Clean Leather", "Sleek Lines"],
    stockQuantity: 0,
    brand: "SofaLux",
    warranty: "4 years",
    reviews: [],
  },
  {
    name: "Urban Compact Sofa Bed",
    slug: "urban-compact-sofa-bed",
    description: "A space-saving sofa bed for small Nairobi apartments.",
    price: 79999,
    category: "Sofa Bed",
    images: [
      "/sofa-bed.jpg",
      "/recliner-sofa.jpg"
    ],
    material: "Fabric",
    colors: ["Gray", "Blue"],
    inStock: true,
    seatingCapacity: 2,
    features: ["Quick-Fold Bed", "Compact Design", "Soft Cushions"],
    stockQuantity: 50,
    brand: "Urban Living",
    warranty: "1 year",
    reviews: [],
  },
  {
    name: "SofaLux Coastal L-Shaped",
    slug: "sofalux-coastal-l-shaped",
    description: "An L-shaped sofa with a breezy, coastal-inspired design.",
    price: 179999,
    category: "L-Shaped",
    images: [
      "/l-shaped.jpg",
      "/sofa-bed.jpg",
    ],
    material: "Fabric",
    colors: ["Beige", "White"],
    inStock: true,
    seatingCapacity: 6,
    features: ["Corner Fit", "Plush Cushions", "Breathable Fabric"],
    stockQuantity: 10,
    brand: "SofaLux",
    warranty: "3 years",
    reviews: [],
  },
  {
    name: "Classic Tufted Comfort",
    slug: "classic-tufted-comfort",
    description: "A tufted fabric sofa with timeless charm.",
    price: 119999,
    category: "Chesterfield",
    images: [
      "/tufted-sofa.jpg",
      "/sofa-bed.jpg",
    ],
    material: "Fabric",
    colors: ["Blue", "Gray"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Tufted Backrest", "Hardwood Frame", "Elegant Design"],
    stockQuantity: 12,
    brand: "Heritage Homes",
    warranty: "3 years",
    reviews: [],
  },
  {
    name: "SofaLux Sleek Modular",
    slug: "sofalux-sleek-modular",
    description: "A modular sofa for customizable layouts in modern homes.",
    price: 249999,
    category: "Modular",
    images: [
      "/recliner-sofa.jpg",
      "/tufted-sofa.jpg"
    ],
    material: "Fabric",
    colors: ["Black", "Gray"],
    inStock: true,
    seatingCapacity: 4,
    features: ["Reconfigurable Sections", "High-Density Foam", "Modern Style"],
    stockQuantity: 7,
    brand: "SofaLux",
    warranty: "4 years",
    reviews: [],
  },
  {
    name: "Boho Oasis Sofa",
    slug: "boho-oasis-sofa",
    description: "A bohemian-style sofa with vibrant, textured fabric.",
    price: 89999,
    category: "Stationary",
    images: [
      "/gray-sofa.jpg",
      "/tufted-sofa.jpg"
    ],
    material: "Fabric",
    colors: ["Multicolor", "Beige"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Textured Fabric", "Boho Patterns", "Comfortable Seating"],
    stockQuantity: 30,
    brand: "Artisan Homes",
    warranty: "2 years",
    reviews: [],
  },
  {
    name: "Industrial Edge Sofa",
    slug: "industrial-edge-sofa",
    description: "An industrial-style sofa with metal frame accents.",
    price: 129999,
    category: "Stationary",
    images: [
      "/gray-sofa.jpg",
      "/tufted-sofa.jpg"
    ],
    material: "Metal",
    colors: ["Gray", "Black"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Metal Frame", "Rugged Design", "Firm Cushions"],
    stockQuantity: 15,
    brand: "Urban Forge",
    warranty: "3 years",
    reviews: [],
  },
  {
    name: "SofaLux Blush Loveseat",
    slug: "sofalux-blush-loveseat",
    description: "A cozy loveseat in soft pink for intimate spaces.",
    price: 69999,
    category: "Loveseat",
    images: [
      "/classic.jpg",
      "/tufted-sofa.jpg"
    ],
    material: "Fabric",
    colors: ["Pink", "Gray"],
    inStock: false,
    seatingCapacity: 2,
    features: ["Soft Fabric", "Compact Size", "Chic Design"],
    stockQuantity: 0,
    brand: "SofaLux",
    warranty: "1 year",
    reviews: [],
  },
  {
    name: "SofaLux Regal Chaise",
    slug: "sofalux-regal-chaise",
    description: "An elegant chaise lounge for luxurious relaxation.",
    price: 149999,
    category: "Single-Seater",
    images: [
      "/chaise.jpg",
      "/classic.jpg"
    ],
    material: "Leather",
    colors: ["Black", "White"],
    inStock: true,
    seatingCapacity: 1,
    features: ["Ergonomic Design", "Premium Leather", "Decorative Stitching"],
    stockQuantity: 10,
    brand: "SofaLux",
    warranty: "4 years",
    reviews: [],
  },
  {
    name: "SofaLux Minimal Sleeper",
    slug: "sofalux-minimal-sleeper",
    description: "A minimalist sleeper sofa for modern guest rooms.",
    price: 129999,
    category: "Sofa Bed",
    images: [
      "/velvet-sofa.jpg",
      "/classic.jpg"
    ],
    material: "Fabric",
    colors: ["White", "Gray"],
    inStock: true,
    seatingCapacity: 3,
    features: ["Foldable Bed", "Minimalist Design", "Soft Cushions"],
    stockQuantity: 40,
    brand: "SofaLux",
    warranty: "2 years",
    reviews: [],
  },
];

async function addProducts() {
  try {
    for (const product of sofas) {
      const response = await fetch(`${API_BASE_URL}/products`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(product),
      });
      const data = await response.json();
      if (response.ok) {
        console.log(`Added: ${product.name}`);
      } else {
        console.error(`Failed to add ${product.name}:`, data.message);
      }
    }
  } catch (error) {
    console.error("Error adding products:", error);
  }
}
addProducts();